image: "node:alpine"
build_signed:
  only:
    refs:
      - master
  artifacts:
    paths:
      - artifacts
  script:
    - yarn install
    - npm run build:prod:firefox
    - npx web-ext build
    - npx web-ext sign --api-key $WEB_EXT_API_KEY --api-secret $WEB_EXT_API_SECRET --channel unlisted --id $WEB_EXT_ID
    - node ./scripts/ff-update-manifest.js
    - mkdir artifacts
    - cp ./updates.json ./artifacts/
    - cp ./web-ext-artifacts/*.xpi ./artifacts/